name: Patch VBMeta

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
 
    - name: Check Out
      uses: actions/checkout@v3.1.0
      
    - name: Operating System Information
      run: |
        uname -a
        
    - name: Patch File Information
      run: |
        file arm64-v8a/vbmeta-disable-verification
        
    - name: Give Permission and Run Patch
      run: |
        chmod +x x86_64/vbmeta-disable-verification
        ./arm64-v8a/vbmeta-disable-verification vbmeta.img

    - name: Upload Patched VBMeta
      uses: actions/upload-artifact@v4
      with:
        name: patched-vbmeta
        path: vbmeta.img
